apiVersion: v1
kind: Service
metadata:
  name: mysql-h
spec:
  selector:
    app: mysql
  ports:
    - name: goserver-service
      port: 80
      targetPort: 8000
      protocol: TCP
  clusterIP: None